import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google"
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Sidebar, { SidebarItem } from "@/components/sidebar";
import { BarChart, CircleUserRound, HouseIcon, Package } from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
  variable: "--font-poppins",
})

const inter = Inter({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"],
  variable: "--font-inter",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased h-screen ${poppins.variable} ${inter.variable}`}
      >

        <NextTopLoader height={5} color="#FFB300" showSpinner={false} ></NextTopLoader>
        <Sidebar>
          <SidebarItem icon={<HouseIcon />} text={"Home"} active alert={false} link={"/"} />
          <SidebarItem icon={<Package />} text={"Estoque"} alert={false} link={"/stock"} />
          <hr />
          <SidebarItem icon={<CircleUserRound />} text={"Perfil"} alert={false} link={"/profile"} />
          </Sidebar >
        {children}
      </body>
    </html>
  );
}
